// Generated by CoffeeScript 1.4.0
(function() {
  var first;

  first = true;

  window.$myfun = function() {
    if (first) {
      setTimeout((function() {
        return $foo();
      }), 1000);
      return first = false;
    } else {
      return $foo();
    }
  };

}).call(this);
