// Generated by CoffeeScript 1.4.0
(function() {

  $pz.resources = function() {
    return [
      {
        file: "mathjax.js",
        fromPage: true
      }, {
        url: "/jslib/vkbeautify.0.99.00.beta.js"
      }
    ];
  };

}).call(this);
